version: 0.1

lint:
  definitions:
    - name: vale
      files: [ALL]
      description: Enforce editorial standards in your text documents
      commands:
        - name: lint
          output: regex
          parse_regex: (?P<path>.*):(?P<line>\d+):(?P<col>\d+):(?P<severity>[^:]+):(?P<message>.+)
          run: vale --output=line ${target}
          success_codes: [0, 1]
          read_output_from: stdout
          batch: true
      suggest_if: config_present
      tools: [vale]
      known_good_version: 3.4.1
      direct_configs: [.vale.ini]
